[user]
nickname = "r0flcat"
username = "r0fltest"
password = ""
realname = "moaw"

[server]
hostname = "irc.snoonet.org"
port = 6697
tls = true
sasl = true
channels = ["#linuxmasterrace"]

[settings]
prefix = '_'
