[default]
[default.user]
nickname = "\\__{^-_-^}"
username = "catinator/irc.snoonet.org"
realname = "moaw"

[default.server]
hostname = "10.10.0.1"
port = 6667
tls = false
sasl = false

[default.settings]
prefix = ':'

[release]
[release.user]
nickname = "\\__{^-_-^}"
[release.server]
channels = ["#redoxmasterrace", "#linuxmasterrace", "#gnulag"]
